name: Deploy Azure Function

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Get Source Code
      uses: actions/checkout@v1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108

    - name: Build with dotnet
      run: dotnet build ./src --configuration Release --output ./output

    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Publish Azure Function
      uses: Azure/functions-action@v1
      id: publish
      with:
        app-name: ${{ secrets.FUNCTION_APP_NAME }}
        package: './output'

    - name: Write Out Function URL
      run: |
        echo "${{ steps.publish.outputs.app-url }}"